// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temporary.proto

package temporary;

public final class Temporary {
  private Temporary() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WebAppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:temporary.WebApp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string appName = 1;</code>
     */
    boolean hasAppName();
    /**
     * <code>required string appName = 1;</code>
     */
    java.lang.String getAppName();
    /**
     * <code>required string appName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
     */
    boolean hasIndexFile();
    /**
     * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
     */
    java.lang.String getIndexFile();
    /**
     * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
     */
    com.google.protobuf.ByteString
        getIndexFileBytes();

    /**
     * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
     */
    boolean hasIndexFileAndroid();
    /**
     * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
     */
    java.lang.String getIndexFileAndroid();
    /**
     * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
     */
    com.google.protobuf.ByteString
        getIndexFileAndroidBytes();

    /**
     * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
     */
    boolean hasIndexFileIos();
    /**
     * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
     */
    java.lang.String getIndexFileIos();
    /**
     * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
     */
    com.google.protobuf.ByteString
        getIndexFileIosBytes();

    /**
     * <code>optional string MainClass = 5 [default = "main"];</code>
     */
    boolean hasMainClass();
    /**
     * <code>optional string MainClass = 5 [default = "main"];</code>
     */
    java.lang.String getMainClass();
    /**
     * <code>optional string MainClass = 5 [default = "main"];</code>
     */
    com.google.protobuf.ByteString
        getMainClassBytes();

    /**
     * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
     */
    boolean hasMainAndroidClass();
    /**
     * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
     */
    java.lang.String getMainAndroidClass();
    /**
     * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
     */
    com.google.protobuf.ByteString
        getMainAndroidClassBytes();

    /**
     * <code>optional string MainIosClass = 7 [default = "main"];</code>
     */
    boolean hasMainIosClass();
    /**
     * <code>optional string MainIosClass = 7 [default = "main"];</code>
     */
    java.lang.String getMainIosClass();
    /**
     * <code>optional string MainIosClass = 7 [default = "main"];</code>
     */
    com.google.protobuf.ByteString
        getMainIosClassBytes();
  }
  /**
   * Protobuf type {@code temporary.WebApp}
   */
  public static final class WebApp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:temporary.WebApp)
      WebAppOrBuilder {
    // Use WebApp.newBuilder() to construct.
    private WebApp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WebApp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WebApp defaultInstance;
    public static WebApp getDefaultInstance() {
      return defaultInstance;
    }

    public WebApp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WebApp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              appName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              indexFile_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              indexFileAndroid_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              indexFileIos_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              mainClass_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              mainAndroidClass_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              mainIosClass_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temporary.Temporary.internal_static_temporary_WebApp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temporary.Temporary.internal_static_temporary_WebApp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              temporary.Temporary.WebApp.class, temporary.Temporary.WebApp.Builder.class);
    }

    public static com.google.protobuf.Parser<WebApp> PARSER =
        new com.google.protobuf.AbstractParser<WebApp>() {
      public WebApp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebApp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WebApp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int APPNAME_FIELD_NUMBER = 1;
    private java.lang.Object appName_;
    /**
     * <code>required string appName = 1;</code>
     */
    public boolean hasAppName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string appName = 1;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXFILE_FIELD_NUMBER = 2;
    private java.lang.Object indexFile_;
    /**
     * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
     */
    public boolean hasIndexFile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
     */
    public java.lang.String getIndexFile() {
      java.lang.Object ref = indexFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indexFile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
     */
    public com.google.protobuf.ByteString
        getIndexFileBytes() {
      java.lang.Object ref = indexFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indexFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXFILEANDROID_FIELD_NUMBER = 3;
    private java.lang.Object indexFileAndroid_;
    /**
     * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
     */
    public boolean hasIndexFileAndroid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
     */
    public java.lang.String getIndexFileAndroid() {
      java.lang.Object ref = indexFileAndroid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indexFileAndroid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
     */
    public com.google.protobuf.ByteString
        getIndexFileAndroidBytes() {
      java.lang.Object ref = indexFileAndroid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indexFileAndroid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXFILEIOS_FIELD_NUMBER = 4;
    private java.lang.Object indexFileIos_;
    /**
     * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
     */
    public boolean hasIndexFileIos() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
     */
    public java.lang.String getIndexFileIos() {
      java.lang.Object ref = indexFileIos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indexFileIos_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
     */
    public com.google.protobuf.ByteString
        getIndexFileIosBytes() {
      java.lang.Object ref = indexFileIos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indexFileIos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAINCLASS_FIELD_NUMBER = 5;
    private java.lang.Object mainClass_;
    /**
     * <code>optional string MainClass = 5 [default = "main"];</code>
     */
    public boolean hasMainClass() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string MainClass = 5 [default = "main"];</code>
     */
    public java.lang.String getMainClass() {
      java.lang.Object ref = mainClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mainClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MainClass = 5 [default = "main"];</code>
     */
    public com.google.protobuf.ByteString
        getMainClassBytes() {
      java.lang.Object ref = mainClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAINANDROIDCLASS_FIELD_NUMBER = 6;
    private java.lang.Object mainAndroidClass_;
    /**
     * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
     */
    public boolean hasMainAndroidClass() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
     */
    public java.lang.String getMainAndroidClass() {
      java.lang.Object ref = mainAndroidClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mainAndroidClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
     */
    public com.google.protobuf.ByteString
        getMainAndroidClassBytes() {
      java.lang.Object ref = mainAndroidClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainAndroidClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAINIOSCLASS_FIELD_NUMBER = 7;
    private java.lang.Object mainIosClass_;
    /**
     * <code>optional string MainIosClass = 7 [default = "main"];</code>
     */
    public boolean hasMainIosClass() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string MainIosClass = 7 [default = "main"];</code>
     */
    public java.lang.String getMainIosClass() {
      java.lang.Object ref = mainIosClass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mainIosClass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MainIosClass = 7 [default = "main"];</code>
     */
    public com.google.protobuf.ByteString
        getMainIosClassBytes() {
      java.lang.Object ref = mainIosClass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainIosClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      appName_ = "";
      indexFile_ = "index.bundle";
      indexFileAndroid_ = "index.android.bundle";
      indexFileIos_ = "index.ios.bundle";
      mainClass_ = "main";
      mainAndroidClass_ = "main";
      mainIosClass_ = "main";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAppName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIndexFileBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIndexFileAndroidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIndexFileIosBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMainClassBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getMainAndroidClassBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMainIosClassBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAppNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIndexFileBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIndexFileAndroidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIndexFileIosBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMainClassBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getMainAndroidClassBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMainIosClassBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static temporary.Temporary.WebApp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static temporary.Temporary.WebApp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static temporary.Temporary.WebApp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static temporary.Temporary.WebApp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static temporary.Temporary.WebApp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static temporary.Temporary.WebApp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static temporary.Temporary.WebApp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static temporary.Temporary.WebApp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static temporary.Temporary.WebApp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static temporary.Temporary.WebApp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temporary.Temporary.WebApp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code temporary.WebApp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:temporary.WebApp)
        temporary.Temporary.WebAppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temporary.Temporary.internal_static_temporary_WebApp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temporary.Temporary.internal_static_temporary_WebApp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                temporary.Temporary.WebApp.class, temporary.Temporary.WebApp.Builder.class);
      }

      // Construct using temporary.Temporary.WebApp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        indexFile_ = "index.bundle";
        bitField0_ = (bitField0_ & ~0x00000002);
        indexFileAndroid_ = "index.android.bundle";
        bitField0_ = (bitField0_ & ~0x00000004);
        indexFileIos_ = "index.ios.bundle";
        bitField0_ = (bitField0_ & ~0x00000008);
        mainClass_ = "main";
        bitField0_ = (bitField0_ & ~0x00000010);
        mainAndroidClass_ = "main";
        bitField0_ = (bitField0_ & ~0x00000020);
        mainIosClass_ = "main";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temporary.Temporary.internal_static_temporary_WebApp_descriptor;
      }

      public temporary.Temporary.WebApp getDefaultInstanceForType() {
        return temporary.Temporary.WebApp.getDefaultInstance();
      }

      public temporary.Temporary.WebApp build() {
        temporary.Temporary.WebApp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public temporary.Temporary.WebApp buildPartial() {
        temporary.Temporary.WebApp result = new temporary.Temporary.WebApp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appName_ = appName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.indexFile_ = indexFile_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.indexFileAndroid_ = indexFileAndroid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.indexFileIos_ = indexFileIos_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mainClass_ = mainClass_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.mainAndroidClass_ = mainAndroidClass_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.mainIosClass_ = mainIosClass_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temporary.Temporary.WebApp) {
          return mergeFrom((temporary.Temporary.WebApp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(temporary.Temporary.WebApp other) {
        if (other == temporary.Temporary.WebApp.getDefaultInstance()) return this;
        if (other.hasAppName()) {
          bitField0_ |= 0x00000001;
          appName_ = other.appName_;
          onChanged();
        }
        if (other.hasIndexFile()) {
          bitField0_ |= 0x00000002;
          indexFile_ = other.indexFile_;
          onChanged();
        }
        if (other.hasIndexFileAndroid()) {
          bitField0_ |= 0x00000004;
          indexFileAndroid_ = other.indexFileAndroid_;
          onChanged();
        }
        if (other.hasIndexFileIos()) {
          bitField0_ |= 0x00000008;
          indexFileIos_ = other.indexFileIos_;
          onChanged();
        }
        if (other.hasMainClass()) {
          bitField0_ |= 0x00000010;
          mainClass_ = other.mainClass_;
          onChanged();
        }
        if (other.hasMainAndroidClass()) {
          bitField0_ |= 0x00000020;
          mainAndroidClass_ = other.mainAndroidClass_;
          onChanged();
        }
        if (other.hasMainIosClass()) {
          bitField0_ |= 0x00000040;
          mainIosClass_ = other.mainIosClass_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        temporary.Temporary.WebApp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (temporary.Temporary.WebApp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appName_ = "";
      /**
       * <code>required string appName = 1;</code>
       */
      public boolean hasAppName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string appName = 1;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appName = 1;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appName = 1;</code>
       */
      public Builder clearAppName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>required string appName = 1;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object indexFile_ = "index.bundle";
      /**
       * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
       */
      public boolean hasIndexFile() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
       */
      public java.lang.String getIndexFile() {
        java.lang.Object ref = indexFile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            indexFile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
       */
      public com.google.protobuf.ByteString
          getIndexFileBytes() {
        java.lang.Object ref = indexFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indexFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
       */
      public Builder setIndexFile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        indexFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
       */
      public Builder clearIndexFile() {
        bitField0_ = (bitField0_ & ~0x00000002);
        indexFile_ = getDefaultInstance().getIndexFile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string indexFile = 2 [default = "index.bundle"];</code>
       */
      public Builder setIndexFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        indexFile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object indexFileAndroid_ = "index.android.bundle";
      /**
       * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
       */
      public boolean hasIndexFileAndroid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
       */
      public java.lang.String getIndexFileAndroid() {
        java.lang.Object ref = indexFileAndroid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            indexFileAndroid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
       */
      public com.google.protobuf.ByteString
          getIndexFileAndroidBytes() {
        java.lang.Object ref = indexFileAndroid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indexFileAndroid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
       */
      public Builder setIndexFileAndroid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        indexFileAndroid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
       */
      public Builder clearIndexFileAndroid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        indexFileAndroid_ = getDefaultInstance().getIndexFileAndroid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string indexFileAndroid = 3 [default = "index.android.bundle"];</code>
       */
      public Builder setIndexFileAndroidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        indexFileAndroid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object indexFileIos_ = "index.ios.bundle";
      /**
       * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
       */
      public boolean hasIndexFileIos() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
       */
      public java.lang.String getIndexFileIos() {
        java.lang.Object ref = indexFileIos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            indexFileIos_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
       */
      public com.google.protobuf.ByteString
          getIndexFileIosBytes() {
        java.lang.Object ref = indexFileIos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indexFileIos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
       */
      public Builder setIndexFileIos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        indexFileIos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
       */
      public Builder clearIndexFileIos() {
        bitField0_ = (bitField0_ & ~0x00000008);
        indexFileIos_ = getDefaultInstance().getIndexFileIos();
        onChanged();
        return this;
      }
      /**
       * <code>optional string indexFileIos = 4 [default = "index.ios.bundle"];</code>
       */
      public Builder setIndexFileIosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        indexFileIos_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mainClass_ = "main";
      /**
       * <code>optional string MainClass = 5 [default = "main"];</code>
       */
      public boolean hasMainClass() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string MainClass = 5 [default = "main"];</code>
       */
      public java.lang.String getMainClass() {
        java.lang.Object ref = mainClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mainClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MainClass = 5 [default = "main"];</code>
       */
      public com.google.protobuf.ByteString
          getMainClassBytes() {
        java.lang.Object ref = mainClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MainClass = 5 [default = "main"];</code>
       */
      public Builder setMainClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mainClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MainClass = 5 [default = "main"];</code>
       */
      public Builder clearMainClass() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mainClass_ = getDefaultInstance().getMainClass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MainClass = 5 [default = "main"];</code>
       */
      public Builder setMainClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mainClass_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mainAndroidClass_ = "main";
      /**
       * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
       */
      public boolean hasMainAndroidClass() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
       */
      public java.lang.String getMainAndroidClass() {
        java.lang.Object ref = mainAndroidClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mainAndroidClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
       */
      public com.google.protobuf.ByteString
          getMainAndroidClassBytes() {
        java.lang.Object ref = mainAndroidClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainAndroidClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
       */
      public Builder setMainAndroidClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        mainAndroidClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
       */
      public Builder clearMainAndroidClass() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mainAndroidClass_ = getDefaultInstance().getMainAndroidClass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MainAndroidClass = 6 [default = "main"];</code>
       */
      public Builder setMainAndroidClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        mainAndroidClass_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mainIosClass_ = "main";
      /**
       * <code>optional string MainIosClass = 7 [default = "main"];</code>
       */
      public boolean hasMainIosClass() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string MainIosClass = 7 [default = "main"];</code>
       */
      public java.lang.String getMainIosClass() {
        java.lang.Object ref = mainIosClass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mainIosClass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MainIosClass = 7 [default = "main"];</code>
       */
      public com.google.protobuf.ByteString
          getMainIosClassBytes() {
        java.lang.Object ref = mainIosClass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mainIosClass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MainIosClass = 7 [default = "main"];</code>
       */
      public Builder setMainIosClass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        mainIosClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MainIosClass = 7 [default = "main"];</code>
       */
      public Builder clearMainIosClass() {
        bitField0_ = (bitField0_ & ~0x00000040);
        mainIosClass_ = getDefaultInstance().getMainIosClass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MainIosClass = 7 [default = "main"];</code>
       */
      public Builder setMainIosClassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        mainIosClass_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:temporary.WebApp)
    }

    static {
      defaultInstance = new WebApp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:temporary.WebApp)
  }

  public interface AppListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:temporary.AppList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    java.util.List<temporary.Temporary.WebApp> 
        getAppList();
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    temporary.Temporary.WebApp getApp(int index);
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    int getAppCount();
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    java.util.List<? extends temporary.Temporary.WebAppOrBuilder> 
        getAppOrBuilderList();
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    temporary.Temporary.WebAppOrBuilder getAppOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code temporary.AppList}
   */
  public static final class AppList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:temporary.AppList)
      AppListOrBuilder {
    // Use AppList.newBuilder() to construct.
    private AppList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppList defaultInstance;
    public static AppList getDefaultInstance() {
      return defaultInstance;
    }

    public AppList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                app_ = new java.util.ArrayList<temporary.Temporary.WebApp>();
                mutable_bitField0_ |= 0x00000001;
              }
              app_.add(input.readMessage(temporary.Temporary.WebApp.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          app_ = java.util.Collections.unmodifiableList(app_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temporary.Temporary.internal_static_temporary_AppList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temporary.Temporary.internal_static_temporary_AppList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              temporary.Temporary.AppList.class, temporary.Temporary.AppList.Builder.class);
    }

    public static com.google.protobuf.Parser<AppList> PARSER =
        new com.google.protobuf.AbstractParser<AppList>() {
      public AppList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppList> getParserForType() {
      return PARSER;
    }

    public static final int APP_FIELD_NUMBER = 1;
    private java.util.List<temporary.Temporary.WebApp> app_;
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    public java.util.List<temporary.Temporary.WebApp> getAppList() {
      return app_;
    }
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    public java.util.List<? extends temporary.Temporary.WebAppOrBuilder> 
        getAppOrBuilderList() {
      return app_;
    }
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    public int getAppCount() {
      return app_.size();
    }
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    public temporary.Temporary.WebApp getApp(int index) {
      return app_.get(index);
    }
    /**
     * <code>repeated .temporary.WebApp app = 1;</code>
     */
    public temporary.Temporary.WebAppOrBuilder getAppOrBuilder(
        int index) {
      return app_.get(index);
    }

    private void initFields() {
      app_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAppCount(); i++) {
        if (!getApp(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < app_.size(); i++) {
        output.writeMessage(1, app_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < app_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, app_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static temporary.Temporary.AppList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static temporary.Temporary.AppList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static temporary.Temporary.AppList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static temporary.Temporary.AppList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static temporary.Temporary.AppList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static temporary.Temporary.AppList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static temporary.Temporary.AppList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static temporary.Temporary.AppList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static temporary.Temporary.AppList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static temporary.Temporary.AppList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(temporary.Temporary.AppList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code temporary.AppList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:temporary.AppList)
        temporary.Temporary.AppListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return temporary.Temporary.internal_static_temporary_AppList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return temporary.Temporary.internal_static_temporary_AppList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                temporary.Temporary.AppList.class, temporary.Temporary.AppList.Builder.class);
      }

      // Construct using temporary.Temporary.AppList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAppFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (appBuilder_ == null) {
          app_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          appBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return temporary.Temporary.internal_static_temporary_AppList_descriptor;
      }

      public temporary.Temporary.AppList getDefaultInstanceForType() {
        return temporary.Temporary.AppList.getDefaultInstance();
      }

      public temporary.Temporary.AppList build() {
        temporary.Temporary.AppList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public temporary.Temporary.AppList buildPartial() {
        temporary.Temporary.AppList result = new temporary.Temporary.AppList(this);
        int from_bitField0_ = bitField0_;
        if (appBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            app_ = java.util.Collections.unmodifiableList(app_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.app_ = app_;
        } else {
          result.app_ = appBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof temporary.Temporary.AppList) {
          return mergeFrom((temporary.Temporary.AppList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(temporary.Temporary.AppList other) {
        if (other == temporary.Temporary.AppList.getDefaultInstance()) return this;
        if (appBuilder_ == null) {
          if (!other.app_.isEmpty()) {
            if (app_.isEmpty()) {
              app_ = other.app_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAppIsMutable();
              app_.addAll(other.app_);
            }
            onChanged();
          }
        } else {
          if (!other.app_.isEmpty()) {
            if (appBuilder_.isEmpty()) {
              appBuilder_.dispose();
              appBuilder_ = null;
              app_ = other.app_;
              bitField0_ = (bitField0_ & ~0x00000001);
              appBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAppFieldBuilder() : null;
            } else {
              appBuilder_.addAllMessages(other.app_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAppCount(); i++) {
          if (!getApp(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        temporary.Temporary.AppList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (temporary.Temporary.AppList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<temporary.Temporary.WebApp> app_ =
        java.util.Collections.emptyList();
      private void ensureAppIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          app_ = new java.util.ArrayList<temporary.Temporary.WebApp>(app_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          temporary.Temporary.WebApp, temporary.Temporary.WebApp.Builder, temporary.Temporary.WebAppOrBuilder> appBuilder_;

      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public java.util.List<temporary.Temporary.WebApp> getAppList() {
        if (appBuilder_ == null) {
          return java.util.Collections.unmodifiableList(app_);
        } else {
          return appBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public int getAppCount() {
        if (appBuilder_ == null) {
          return app_.size();
        } else {
          return appBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public temporary.Temporary.WebApp getApp(int index) {
        if (appBuilder_ == null) {
          return app_.get(index);
        } else {
          return appBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder setApp(
          int index, temporary.Temporary.WebApp value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppIsMutable();
          app_.set(index, value);
          onChanged();
        } else {
          appBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder setApp(
          int index, temporary.Temporary.WebApp.Builder builderForValue) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.set(index, builderForValue.build());
          onChanged();
        } else {
          appBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder addApp(temporary.Temporary.WebApp value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppIsMutable();
          app_.add(value);
          onChanged();
        } else {
          appBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder addApp(
          int index, temporary.Temporary.WebApp value) {
        if (appBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppIsMutable();
          app_.add(index, value);
          onChanged();
        } else {
          appBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder addApp(
          temporary.Temporary.WebApp.Builder builderForValue) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.add(builderForValue.build());
          onChanged();
        } else {
          appBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder addApp(
          int index, temporary.Temporary.WebApp.Builder builderForValue) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.add(index, builderForValue.build());
          onChanged();
        } else {
          appBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder addAllApp(
          java.lang.Iterable<? extends temporary.Temporary.WebApp> values) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, app_);
          onChanged();
        } else {
          appBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder clearApp() {
        if (appBuilder_ == null) {
          app_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          appBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public Builder removeApp(int index) {
        if (appBuilder_ == null) {
          ensureAppIsMutable();
          app_.remove(index);
          onChanged();
        } else {
          appBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public temporary.Temporary.WebApp.Builder getAppBuilder(
          int index) {
        return getAppFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public temporary.Temporary.WebAppOrBuilder getAppOrBuilder(
          int index) {
        if (appBuilder_ == null) {
          return app_.get(index);  } else {
          return appBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public java.util.List<? extends temporary.Temporary.WebAppOrBuilder> 
           getAppOrBuilderList() {
        if (appBuilder_ != null) {
          return appBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(app_);
        }
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public temporary.Temporary.WebApp.Builder addAppBuilder() {
        return getAppFieldBuilder().addBuilder(
            temporary.Temporary.WebApp.getDefaultInstance());
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public temporary.Temporary.WebApp.Builder addAppBuilder(
          int index) {
        return getAppFieldBuilder().addBuilder(
            index, temporary.Temporary.WebApp.getDefaultInstance());
      }
      /**
       * <code>repeated .temporary.WebApp app = 1;</code>
       */
      public java.util.List<temporary.Temporary.WebApp.Builder> 
           getAppBuilderList() {
        return getAppFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          temporary.Temporary.WebApp, temporary.Temporary.WebApp.Builder, temporary.Temporary.WebAppOrBuilder> 
          getAppFieldBuilder() {
        if (appBuilder_ == null) {
          appBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              temporary.Temporary.WebApp, temporary.Temporary.WebApp.Builder, temporary.Temporary.WebAppOrBuilder>(
                  app_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          app_ = null;
        }
        return appBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:temporary.AppList)
    }

    static {
      defaultInstance = new AppList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:temporary.AppList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temporary_WebApp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temporary_WebApp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_temporary_AppList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_temporary_AppList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017temporary.proto\022\ttemporary\"\347\001\n\006WebApp\022" +
      "\017\n\007appName\030\001 \002(\t\022\037\n\tindexFile\030\002 \001(\t:\014ind" +
      "ex.bundle\022.\n\020indexFileAndroid\030\003 \001(\t:\024ind" +
      "ex.android.bundle\022&\n\014indexFileIos\030\004 \001(\t:" +
      "\020index.ios.bundle\022\027\n\tMainClass\030\005 \001(\t:\004ma" +
      "in\022\036\n\020MainAndroidClass\030\006 \001(\t:\004main\022\032\n\014Ma" +
      "inIosClass\030\007 \001(\t:\004main\")\n\007AppList\022\036\n\003app" +
      "\030\001 \003(\0132\021.temporary.WebApp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_temporary_WebApp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_temporary_WebApp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_temporary_WebApp_descriptor,
        new java.lang.String[] { "AppName", "IndexFile", "IndexFileAndroid", "IndexFileIos", "MainClass", "MainAndroidClass", "MainIosClass", });
    internal_static_temporary_AppList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_temporary_AppList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_temporary_AppList_descriptor,
        new java.lang.String[] { "App", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
